Add release workflow for arm

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -265,9 +265,83 @@ jobs:
         run: |
           gh release upload ${{ steps.prep.outputs.version }} testcafe-macos-amd64.zip
 
+  release-macos-arm-bundle:
+    runs-on: macos-latest
+    needs: [create-release-draft]
+    steps:
+      - name: Find matching draft tag
+        # Fetches the `asset_id` of the uploaded bundle. A non-empty `asset_id` signals a successful upload, preventing duplicate uploads in retry attempts.
+        id: prep
+        run: |
+          VERSION=$(curl -s -H "Authorization: token ${{ github.token }}" \
+                      https://api.github.com/repos/${{ github.repository }}/releases | \
+                      jq -r "[.[] | select(.draft == true) | select(.body | contains(\"- jobId: ${{ github.run_id }}\\n\"))] | first | .tag_name")
+          RELEASE_ID=$(curl -s -H "Authorization: token ${{ github.token }}" \
+                      https://api.github.com/repos/${{ github.repository }}/releases | \
+                      jq -r "[.[] | select(.draft == true) | select(.body | contains(\"- jobId: ${{ github.run_id }}\\n\"))] | first | .id")
+
+          if [ "${VERSION}" = "" ];then
+              echo "No draft version found"
+              exit 1
+          fi
+
+          ASSET_ID=$(curl -s -H "Authorization: token ${{ github.token }}" \
+                      https://api.github.com/repos/${{ github.repository }}/releases | \
+                      jq -r "[.[] | select(.body | contains(\"- jobId: ${{ github.run_id }}\\n\"))] | first | .assets | .[] | select(.name == \"testcafe-macos-arm64.zip\") | .id | select(. != null)")
+
+          echo "version=${VERSION}" >> $GITHUB_OUTPUT
+          echo "release_id=${RELEASE_ID}" >> $GITHUB_OUTPUT
+          echo "asset_id=${ASSET_ID}" >> $GITHUB_OUTPUT
+
+      - run: echo "${{ steps.prep.outputs.release_id }} - ${{ steps.prep.outputs.version }} - ${{ steps.prep.outputs.asset_id }}"
+
+      - name: Checkout
+        uses: actions/checkout@v4
+        if: ${{ steps.prep.outputs.asset_id == '' }}
+        with:
+          ref: ${{ steps.prep.outputs.version }}
+
+      - name: Setup Node
+        if: ${{ steps.prep.outputs.asset_id == '' }}
+        uses: actions/setup-node@v4
+        with:
+          node-version-file: ".nvmrc"
+          cache: "npm"
+
+      - name: Update Release version
+        if: ${{ steps.prep.outputs.asset_id == '' }}
+        run: |
+          npm version --no-git-tag-version ${{  steps.prep.outputs.version }}
+
+      - name: Install Dependencies
+        run: npm ci --production
+        env:
+          HUSKY: 0
+        if: ${{ steps.prep.outputs.asset_id == '' }}
+
+      - name: Bundle Directory
+        if: ${{ steps.prep.outputs.asset_id == '' }}
+        run: bash ./scripts/bundle.sh
+
+      - name: List Bundle Contents
+        if: ${{ steps.prep.outputs.asset_id == '' }}
+        run: ls -R bundle/
+
+      - name: Archive Bundle
+        if: ${{ steps.prep.outputs.asset_id == '' }}
+        run: zip -r testcafe-macos-arm64.zip bundle/
+
+      - name: Upload Release Asset
+        if: ${{ steps.prep.outputs.asset_id == '' }}
+        env:
+          GITHUB_TOKEN: ${{ github.token }}
+        run: |
+          gh release upload ${{ steps.prep.outputs.version }} testcafe-macos-arm64.zip
+
+
   publish-release:
     runs-on: ubuntu-latest
-    needs: [release-windows-bundle, release-macos-bundle]
+    needs: [release-windows-bundle, release-macos-bundle, release-macos-arm-bundle]
     steps:
       - name: Find Matching Draft Tag
         id: prep
